import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Livvic } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const livvic = Livvic({
  subsets: ['latin'],
  variable: '--font-livvic',
  style: 'normal',
  weight: ['400', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${livvic.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
